if(NOT EXISTS "${APP_BUNDLE}/Contents/MacOS/OpenGoldBox")
    message(FATAL_ERROR "macOS package is missing its game executable: ${APP_BUNDLE}")
endif()
if(NOT EXISTS "${APP_BUNDLE}/Contents/Resources/data/rules/srd-5.2.1/combat.rules")
    message(FATAL_ERROR "macOS package is missing its rules data: ${APP_BUNDLE}")
endif()
file(GLOB_RECURSE game_libraries "${APP_BUNDLE}/*opengoldbox_game.dylib")
if(NOT game_libraries)
    message(FATAL_ERROR "macOS package is missing its GDExtension library: ${APP_BUNDLE}")
endif()
file(GLOB_RECURSE game_packs "${APP_BUNDLE}/*.pck")
if(NOT game_packs)
    message(FATAL_ERROR "macOS package is missing its packed game assets: ${APP_BUNDLE}")
endif()
